### PR TITLE
Expose `uploads` resource to allow for adding attachments to tickets

### PR DESCRIPTION
**Pull request by rstawarz**
Will be used in doximity: https://github.com/doximity/doximity/compare/rs_get_verified#diff-8e09f11127b984dc0cc5d01ce6d6b11eR1

https://www.pivotaltracker.com/story/show/111113602

### CODE REVIEW

**Comment by rstawarz** [comment]
@brupm @divoxx @jeyb - Care to take a look at this?

**Comment by rafb43** [comment]
:+1: :rocket: :star:

**Comment by brupm** [comment]
:+1: not too familiar with their API by can tests be written against this?

**Comment by rstawarz** [comment]
@brupm - I can add tests, for API integrations like this, I like to use [VCR](https://github.com/vcr/vcr) - any objection?

**Comment by brupm** [comment]
None.

On Thu, Jan 28, 2016 at 3:28 PM, Ryan Stawarz notifications@github.com
wrote:

> @brupm https://github.com/brupm - I can add tests, for API integrations
> like this, I like to use VCR https://github.com/vcr/vcr - any objection?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/doximity/zendesk_api/pull/1#issuecomment-176479105.

## 
- Bruno

**Comment by rstawarz** [comment]
@brupm - I decided `VCR` wasn't worth the effort here.  I didn't want to have to go through the setup to configure the actual credentials inside this repository and keeping them secure.  In any case, I just did a simple web mock.

**Comment by brupm** [comment]
:+1:

**Comment by jeyb** [comment]
:+1:

**Pull request merged**
